module "dist-ng_executor" {
  source = "git@github.com:TheWeatherCompany/tf-module-app.git?ref=0.6.9"
  app-name = "dist-ng_executor"
  environment = "${var.environment}"
  chef_repo = "platform"
  chef_role = "dist-ng_executor"
  region = "${var.region}"
  billing-tag = "SUN"
  node-subnet = "${data.terraform_remote_state.sun-managed-dev-us-east-1.private_2_ids}"
  node-zone = "${data.terraform_remote_state.sun-managed-dev-us-east-1.private_2_zones}"
  zone_id = "${var.zone_id}"
  ssh-key-name = "${var.SSH_KEY_NAME}"
  security_groups = "${data.terraform_remote_state.sun-managed-dev-us-east-1.basic_access_sg},${data.terraform_remote_state.sun-managed-dev-us-east-1.internal_sg}"
  vpc = "${data.terraform_remote_state.sun-managed-dev-us-east-1.vpc_id}"
  bastion_host = "${data.terraform_remote_state.sun-managed-dev-us-east-1.bastion_ip}"
  bastion_user = "ops-user"
  validation_client_name = "${var.validation_client_name}"
  validation_key_path = "${var.validation_key_path}"
  instance_type = "t2.large"
}

module "dist-ng_server" {
  source = "git@github.com:TheWeatherCompany/tf-module-app.git?ref=0.6.9"
  app-name = "dist-ng_server"
  environment = "${var.environment}"
  chef_repo = "platform"
  chef_role = "dist-ng_server"
  region = "${var.region}"
  billing-tag = "SUN"
  node-subnet = "${data.terraform_remote_state.sun-managed-dev-us-east-1.private_2_ids}"
  node-zone = "${data.terraform_remote_state.sun-managed-dev-us-east-1.private_2_zones}"
  zone_id = "${var.zone_id}"
  ssh-key-name = "${var.SSH_KEY_NAME}"
  security_groups = "${data.terraform_remote_state.sun-managed-dev-us-east-1.basic_access_sg},${data.terraform_remote_state.sun-managed-dev-us-east-1.internal_sg}"
  vpc = "${data.terraform_remote_state.sun-managed-dev-us-east-1.vpc_id}"
  bastion_host = "${data.terraform_remote_state.sun-managed-dev-us-east-1.bastion_ip}"
  bastion_user = "ops-user"
  validation_client_name = "${var.validation_client_name}"
  validation_key_path = "${var.validation_key_path}"
  instance_type = "t2.medium"
}

